name: run-frontend-tests

on:
  push:
    branches:
      - v1
      - main
  pull_request:
    branches:
      - v1
      - main
  schedule:
    - cron: '0 9 1 * *'

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Install yarn dependencies
        run: yarn install
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: Build
        run: go build -v ./...

      - name: Build Frontend
        run: yarn build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
